[[WaveFD]]
arch = "aarch64"
git-tree-sha1 = "bd95af65f8daea8b84567da5fdf878ae18d77cf0"
os = "macos"

    [[WaveFD.download]]
    sha256 = "81a56cc3f65b6b4789ba22eb8b44630d05d45ad77829f05c77e9ed609f8ef541"
    url = "https://github.com/JuliaBinaryWrappers/WaveFD_jll.jl/releases/download/WaveFD-v0.5.1+0/WaveFD.v0.5.1.aarch64-apple-darwin.tar.gz"
[[WaveFD]]
arch = "aarch64"
git-tree-sha1 = "c1a2a123ce65e517d57daa7872143cd4701db6ab"
libc = "glibc"
os = "linux"

    [[WaveFD.download]]
    sha256 = "5927d86b4df1c3191f6972ef7b22727b2764391ab54b4ee0a931ef983f689a43"
    url = "https://github.com/JuliaBinaryWrappers/WaveFD_jll.jl/releases/download/WaveFD-v0.5.1+0/WaveFD.v0.5.1.aarch64-linux-gnu.tar.gz"
[[WaveFD]]
arch = "aarch64"
git-tree-sha1 = "8e6f3d8c8d98d78ff589ca64b30aa756da468135"
libc = "musl"
os = "linux"

    [[WaveFD.download]]
    sha256 = "383537520f33f12b589fd396338bfba4f726470db448b27d008eb066e89dab61"
    url = "https://github.com/JuliaBinaryWrappers/WaveFD_jll.jl/releases/download/WaveFD-v0.5.1+0/WaveFD.v0.5.1.aarch64-linux-musl.tar.gz"
[[WaveFD]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "dff70fcc51310b70e563fd25a40741aea4e6f8b0"
libc = "glibc"
os = "linux"

    [[WaveFD.download]]
    sha256 = "18209a6a139bc63adaef1e3f6fe9204c5c6a9ec25b32d64e6df4d9bd070e2e63"
    url = "https://github.com/JuliaBinaryWrappers/WaveFD_jll.jl/releases/download/WaveFD-v0.5.1+0/WaveFD.v0.5.1.armv6l-linux-gnueabihf.tar.gz"
[[WaveFD]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ea90d086654726eb33364f938d4b53ddc939b8aa"
libc = "musl"
os = "linux"

    [[WaveFD.download]]
    sha256 = "2a3dc1e53c70fe40a8a37eaf1b114a8c64a14dd2c15279a2a0e7aeea6146c40a"
    url = "https://github.com/JuliaBinaryWrappers/WaveFD_jll.jl/releases/download/WaveFD-v0.5.1+0/WaveFD.v0.5.1.armv6l-linux-musleabihf.tar.gz"
[[WaveFD]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2a23de9135e1cf5fa66892c1887ce3208695c95d"
libc = "glibc"
os = "linux"

    [[WaveFD.download]]
    sha256 = "9659383df0899d9a4fbf66a83ab779fa635495b5021595c51e3f57e4c021e1e3"
    url = "https://github.com/JuliaBinaryWrappers/WaveFD_jll.jl/releases/download/WaveFD-v0.5.1+0/WaveFD.v0.5.1.armv7l-linux-gnueabihf.tar.gz"
[[WaveFD]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "defe0ff7b06dae09c7705f421f93eb0ebacd69fa"
libc = "musl"
os = "linux"

    [[WaveFD.download]]
    sha256 = "a62ca9e50b99bb475c946da37ce88a26cb09925133776b7de1718c1b9837669d"
    url = "https://github.com/JuliaBinaryWrappers/WaveFD_jll.jl/releases/download/WaveFD-v0.5.1+0/WaveFD.v0.5.1.armv7l-linux-musleabihf.tar.gz"
[[WaveFD]]
arch = "i686"
git-tree-sha1 = "f88bacdba84eff73f2f69c1de144571f9651c2e0"
libc = "glibc"
os = "linux"

    [[WaveFD.download]]
    sha256 = "7982db7955c5937e2981427068050f5b7d1cbe97225840c117d07c6a4997e966"
    url = "https://github.com/JuliaBinaryWrappers/WaveFD_jll.jl/releases/download/WaveFD-v0.5.1+0/WaveFD.v0.5.1.i686-linux-gnu.tar.gz"
[[WaveFD]]
arch = "i686"
git-tree-sha1 = "d3f691b59d03c2116813497aafca1aaa305a0d42"
libc = "musl"
os = "linux"

    [[WaveFD.download]]
    sha256 = "9983ab67720e5f2c79c6d817d95a71dc163da73cbd22d29bef7d99eedb800bb8"
    url = "https://github.com/JuliaBinaryWrappers/WaveFD_jll.jl/releases/download/WaveFD-v0.5.1+0/WaveFD.v0.5.1.i686-linux-musl.tar.gz"
[[WaveFD]]
arch = "i686"
git-tree-sha1 = "2cd1ae55c3d653085b5bd2f0ae4e3d6f0bf73328"
os = "windows"

    [[WaveFD.download]]
    sha256 = "fb7bec7486b8b240d3d4cfd640c937eb23df7ea39d48d090114f1fc801daa526"
    url = "https://github.com/JuliaBinaryWrappers/WaveFD_jll.jl/releases/download/WaveFD-v0.5.1+0/WaveFD.v0.5.1.i686-w64-mingw32.tar.gz"
[[WaveFD]]
arch = "powerpc64le"
git-tree-sha1 = "c814480170ad4527e2fdd2bbd1e117730f8faff4"
libc = "glibc"
os = "linux"

    [[WaveFD.download]]
    sha256 = "44d7cde83f548c1f23a7493a0757dbd06a4974cdda3d044f15048ce69fdca04f"
    url = "https://github.com/JuliaBinaryWrappers/WaveFD_jll.jl/releases/download/WaveFD-v0.5.1+0/WaveFD.v0.5.1.powerpc64le-linux-gnu.tar.gz"
[[WaveFD]]
arch = "x86_64"
git-tree-sha1 = "5fdc54510d539a7133dff7dd12f777f1c426d3e7"
os = "macos"

    [[WaveFD.download]]
    sha256 = "5265a0b86a8d2e457079109d1b69f3c4a769491056bf30dcd8607578cee23e4c"
    url = "https://github.com/JuliaBinaryWrappers/WaveFD_jll.jl/releases/download/WaveFD-v0.5.1+0/WaveFD.v0.5.1.x86_64-apple-darwin.tar.gz"
[[WaveFD]]
arch = "x86_64"
git-tree-sha1 = "33a64de4eb4d7a17eba34408e0a03b530d8142ac"
libc = "glibc"
os = "linux"

    [[WaveFD.download]]
    sha256 = "38eeb1debd6a8da75d6a9dc52f16272e420785b7782ee6b6fe404beab0a9e673"
    url = "https://github.com/JuliaBinaryWrappers/WaveFD_jll.jl/releases/download/WaveFD-v0.5.1+0/WaveFD.v0.5.1.x86_64-linux-gnu.tar.gz"
[[WaveFD]]
arch = "x86_64"
git-tree-sha1 = "318232a79bd6f9159b8bc27b968baa6bcd2fdbe3"
libc = "musl"
os = "linux"

    [[WaveFD.download]]
    sha256 = "5a2ee55c1acbf777d1525ebaef9de25eef41510ee45ff8d13f5a0a6a9de54798"
    url = "https://github.com/JuliaBinaryWrappers/WaveFD_jll.jl/releases/download/WaveFD-v0.5.1+0/WaveFD.v0.5.1.x86_64-linux-musl.tar.gz"
[[WaveFD]]
arch = "x86_64"
git-tree-sha1 = "8a9a336b9838ce8380e83a52063052399e741bc7"
os = "freebsd"

    [[WaveFD.download]]
    sha256 = "f653d86a94d7985b00e7c9d09bf6d28d904436a1c6547620d7f52d3652c50c26"
    url = "https://github.com/JuliaBinaryWrappers/WaveFD_jll.jl/releases/download/WaveFD-v0.5.1+0/WaveFD.v0.5.1.x86_64-unknown-freebsd.tar.gz"
[[WaveFD]]
arch = "x86_64"
git-tree-sha1 = "cd559742ea1e447de5f30aea3e54b0d8fd69aad6"
os = "windows"

    [[WaveFD.download]]
    sha256 = "9eeecbf8f2a2560b9de0b05ad02686bc8fbf18c74d156af0e1072d9678395ec3"
    url = "https://github.com/JuliaBinaryWrappers/WaveFD_jll.jl/releases/download/WaveFD-v0.5.1+0/WaveFD.v0.5.1.x86_64-w64-mingw32.tar.gz"
