[[WaveFD]]
arch = "aarch64"
git-tree-sha1 = "a4baa320b201b0471ab66024fc47dc67cdfda168"
libc = "glibc"
os = "linux"

    [[WaveFD.download]]
    sha256 = "6e74a397b41255eed6f4565b97f5a89dd833ae6d2b652d1308b4b637e6b9da76"
    url = "https://github.com/JuliaBinaryWrappers/WaveFD_jll.jl/releases/download/WaveFD-v0.2.0+0/WaveFD.v0.2.0.aarch64-linux-gnu.tar.gz"
[[WaveFD]]
arch = "aarch64"
git-tree-sha1 = "927f43ffd44385029d79c5aeac0f883a8b3b62ad"
libc = "musl"
os = "linux"

    [[WaveFD.download]]
    sha256 = "cdb9c609d57ecdee58be4e381eb82c67d007f287855c4829eb6d3f568cd0971f"
    url = "https://github.com/JuliaBinaryWrappers/WaveFD_jll.jl/releases/download/WaveFD-v0.2.0+0/WaveFD.v0.2.0.aarch64-linux-musl.tar.gz"
[[WaveFD]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b02f0e23548686db396995001596024785d1711e"
libc = "glibc"
os = "linux"

    [[WaveFD.download]]
    sha256 = "e238595aa02c3a5c1a446e2b799a44c4f532446aead39ea27b975d697dddcf9d"
    url = "https://github.com/JuliaBinaryWrappers/WaveFD_jll.jl/releases/download/WaveFD-v0.2.0+0/WaveFD.v0.2.0.armv7l-linux-gnueabihf.tar.gz"
[[WaveFD]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7f46b2a1d2f43b323567c45e81bba1736e4142c2"
libc = "musl"
os = "linux"

    [[WaveFD.download]]
    sha256 = "40ec37770dfa22d405a4562aeb36bc021f9471d57ff2cd5665e574db8b7d6aa4"
    url = "https://github.com/JuliaBinaryWrappers/WaveFD_jll.jl/releases/download/WaveFD-v0.2.0+0/WaveFD.v0.2.0.armv7l-linux-musleabihf.tar.gz"
[[WaveFD]]
arch = "i686"
git-tree-sha1 = "7191057271fe335855d2011ace6efe45e3862060"
libc = "glibc"
os = "linux"

    [[WaveFD.download]]
    sha256 = "1cd9044b17e153495e2fb63d37f1544afb26a612ba798a72fc3758b1b45c7697"
    url = "https://github.com/JuliaBinaryWrappers/WaveFD_jll.jl/releases/download/WaveFD-v0.2.0+0/WaveFD.v0.2.0.i686-linux-gnu.tar.gz"
[[WaveFD]]
arch = "i686"
git-tree-sha1 = "85179bcb4ce3b6819834265e2bce57738f5642ba"
libc = "musl"
os = "linux"

    [[WaveFD.download]]
    sha256 = "acc349789a1093a27aaef2a9f609291e5ec3ede03f21f4396d3d8e469975753a"
    url = "https://github.com/JuliaBinaryWrappers/WaveFD_jll.jl/releases/download/WaveFD-v0.2.0+0/WaveFD.v0.2.0.i686-linux-musl.tar.gz"
[[WaveFD]]
arch = "i686"
git-tree-sha1 = "ff920c68c5e2b34d0245c9da763c610c2aa702f6"
os = "windows"

    [[WaveFD.download]]
    sha256 = "aec6438e1457f9a305a5ccf50a305ef37ba9385144156d8803cfcb2090a9968b"
    url = "https://github.com/JuliaBinaryWrappers/WaveFD_jll.jl/releases/download/WaveFD-v0.2.0+0/WaveFD.v0.2.0.i686-w64-mingw32.tar.gz"
[[WaveFD]]
arch = "powerpc64le"
git-tree-sha1 = "37f5822d90dde3d64204797d606b4ba84c787882"
libc = "glibc"
os = "linux"

    [[WaveFD.download]]
    sha256 = "eeaa93465c90aa08baaf859c2679b11b2b89bf65fe396f7ba793a97439761c21"
    url = "https://github.com/JuliaBinaryWrappers/WaveFD_jll.jl/releases/download/WaveFD-v0.2.0+0/WaveFD.v0.2.0.powerpc64le-linux-gnu.tar.gz"
[[WaveFD]]
arch = "x86_64"
git-tree-sha1 = "b11537e1f7befb6b7b550bc53c8717c53d6aa7e7"
os = "macos"

    [[WaveFD.download]]
    sha256 = "694b639e41623741f5a922c0de63cf8d6e8415983a2f120d06b1a49577071cb8"
    url = "https://github.com/JuliaBinaryWrappers/WaveFD_jll.jl/releases/download/WaveFD-v0.2.0+0/WaveFD.v0.2.0.x86_64-apple-darwin.tar.gz"
[[WaveFD]]
arch = "x86_64"
git-tree-sha1 = "49a5b41ebaecb7a9e2ec207d5d0a4ed0199898e5"
libc = "glibc"
os = "linux"

    [[WaveFD.download]]
    sha256 = "474c66cad621a1fa06d87a4f8e32d4640569a2e158178b7536baefa268383a83"
    url = "https://github.com/JuliaBinaryWrappers/WaveFD_jll.jl/releases/download/WaveFD-v0.2.0+0/WaveFD.v0.2.0.x86_64-linux-gnu.tar.gz"
[[WaveFD]]
arch = "x86_64"
git-tree-sha1 = "87249e67405fe490d5133f7a67be98791ae038b7"
libc = "musl"
os = "linux"

    [[WaveFD.download]]
    sha256 = "4e63b28a9865557e024bfb2b4d37d57afdd682418eedd391b80502b795bcbf5b"
    url = "https://github.com/JuliaBinaryWrappers/WaveFD_jll.jl/releases/download/WaveFD-v0.2.0+0/WaveFD.v0.2.0.x86_64-linux-musl.tar.gz"
[[WaveFD]]
arch = "x86_64"
git-tree-sha1 = "8d9ca108977ccd50f11b19d39f5df98fe7382e6e"
os = "freebsd"

    [[WaveFD.download]]
    sha256 = "a8d85681987415fe483fa165c77b0a50d7b3655c871b3236b1b2babeeb126a03"
    url = "https://github.com/JuliaBinaryWrappers/WaveFD_jll.jl/releases/download/WaveFD-v0.2.0+0/WaveFD.v0.2.0.x86_64-unknown-freebsd.tar.gz"
[[WaveFD]]
arch = "x86_64"
git-tree-sha1 = "398488ff1f3719f30b7d62efed5693d0b407e4ce"
os = "windows"

    [[WaveFD.download]]
    sha256 = "71edb36026d9f8e0b6ec1b5619dde092c952106887f164b19567e9ddb86b3dfc"
    url = "https://github.com/JuliaBinaryWrappers/WaveFD_jll.jl/releases/download/WaveFD-v0.2.0+0/WaveFD.v0.2.0.x86_64-w64-mingw32.tar.gz"
