[[WaveFD]]
arch = "aarch64"
git-tree-sha1 = "87987c920c0196348ec54a05bb97bfb6b169fc35"
libc = "glibc"
os = "linux"

    [[WaveFD.download]]
    sha256 = "8ce122565cd072f1cfe7d3de24f1d30217d54fc04327736ea91808a370a3cefc"
    url = "https://github.com/JuliaBinaryWrappers/WaveFD_jll.jl/releases/download/WaveFD-v0.3.0+0/WaveFD.v0.3.0.aarch64-linux-gnu.tar.gz"
[[WaveFD]]
arch = "aarch64"
git-tree-sha1 = "e6271f7f83ca431158a90fc709c852ec609ddcc0"
libc = "musl"
os = "linux"

    [[WaveFD.download]]
    sha256 = "6435d4d2d54c73c575810a84d4629b691dfedc2c1c43d36cc9728aa77b64e889"
    url = "https://github.com/JuliaBinaryWrappers/WaveFD_jll.jl/releases/download/WaveFD-v0.3.0+0/WaveFD.v0.3.0.aarch64-linux-musl.tar.gz"
[[WaveFD]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0d56007ba59f7e7c11bb11b75843c91f849cf6a5"
libc = "glibc"
os = "linux"

    [[WaveFD.download]]
    sha256 = "87409b11de0f1866c6144a5d84429fe1fac184c57edef97c43eea87a1027d1f6"
    url = "https://github.com/JuliaBinaryWrappers/WaveFD_jll.jl/releases/download/WaveFD-v0.3.0+0/WaveFD.v0.3.0.armv7l-linux-gnueabihf.tar.gz"
[[WaveFD]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6d5b4b755a7a9783488238f3c16b10998d1011b5"
libc = "musl"
os = "linux"

    [[WaveFD.download]]
    sha256 = "8217ccfc68101d3e1be4606c98a7e9251ea0942ddf6c194bea5e76572d552832"
    url = "https://github.com/JuliaBinaryWrappers/WaveFD_jll.jl/releases/download/WaveFD-v0.3.0+0/WaveFD.v0.3.0.armv7l-linux-musleabihf.tar.gz"
[[WaveFD]]
arch = "i686"
git-tree-sha1 = "9b083c6d924258643535e8d9dd5ff5f73f97c497"
libc = "glibc"
os = "linux"

    [[WaveFD.download]]
    sha256 = "bdb3a0612dc57542149876cf8dc0d038ccad62479fc0983b772866e021a8455f"
    url = "https://github.com/JuliaBinaryWrappers/WaveFD_jll.jl/releases/download/WaveFD-v0.3.0+0/WaveFD.v0.3.0.i686-linux-gnu.tar.gz"
[[WaveFD]]
arch = "i686"
git-tree-sha1 = "cbc1ffa5fad00519860863a05e36416c2e7931a2"
libc = "musl"
os = "linux"

    [[WaveFD.download]]
    sha256 = "477a0d8d602ea64a23895e61866c60192cbbe6c52898b822064417e597f81fd8"
    url = "https://github.com/JuliaBinaryWrappers/WaveFD_jll.jl/releases/download/WaveFD-v0.3.0+0/WaveFD.v0.3.0.i686-linux-musl.tar.gz"
[[WaveFD]]
arch = "i686"
git-tree-sha1 = "e67685f9353c03de5c63218663d0c8347d313a69"
os = "windows"

    [[WaveFD.download]]
    sha256 = "a6f51383b4b30dc27fac2cdfa8fbee5274185f575e683479bfe37e2b4a10ff0a"
    url = "https://github.com/JuliaBinaryWrappers/WaveFD_jll.jl/releases/download/WaveFD-v0.3.0+0/WaveFD.v0.3.0.i686-w64-mingw32.tar.gz"
[[WaveFD]]
arch = "powerpc64le"
git-tree-sha1 = "6daf689e3e365ac2c0b197cb88ff660479306f0a"
libc = "glibc"
os = "linux"

    [[WaveFD.download]]
    sha256 = "0c08c822fb011a97d49ecaec3ebabd526321027b48a93aff744cf22bf14e5654"
    url = "https://github.com/JuliaBinaryWrappers/WaveFD_jll.jl/releases/download/WaveFD-v0.3.0+0/WaveFD.v0.3.0.powerpc64le-linux-gnu.tar.gz"
[[WaveFD]]
arch = "x86_64"
git-tree-sha1 = "7471ceca0e160ebc96cf76725dbbd07b4fe722c0"
os = "macos"

    [[WaveFD.download]]
    sha256 = "2726e16f36d3684fb0268bc05f2128a091373f336b6a7cd5e37d022b2e2935cc"
    url = "https://github.com/JuliaBinaryWrappers/WaveFD_jll.jl/releases/download/WaveFD-v0.3.0+0/WaveFD.v0.3.0.x86_64-apple-darwin.tar.gz"
[[WaveFD]]
arch = "x86_64"
git-tree-sha1 = "f3c8c85a51b9f2f37725fc88b51aba205983b127"
libc = "glibc"
os = "linux"

    [[WaveFD.download]]
    sha256 = "417369f7c7e34a6e3a685e6dc2afe2f66c72bf3c2caa935e05c1ef03087dd914"
    url = "https://github.com/JuliaBinaryWrappers/WaveFD_jll.jl/releases/download/WaveFD-v0.3.0+0/WaveFD.v0.3.0.x86_64-linux-gnu.tar.gz"
[[WaveFD]]
arch = "x86_64"
git-tree-sha1 = "a82c904f00872bdb1e761e503a5289c30f2f72cd"
libc = "musl"
os = "linux"

    [[WaveFD.download]]
    sha256 = "2b93a4b07ecf3a32e858b34ebb507db19aa679df471964614c19dbfd791905c3"
    url = "https://github.com/JuliaBinaryWrappers/WaveFD_jll.jl/releases/download/WaveFD-v0.3.0+0/WaveFD.v0.3.0.x86_64-linux-musl.tar.gz"
[[WaveFD]]
arch = "x86_64"
git-tree-sha1 = "29dd2511444d8d8c4dce3f028954b41be6b3d315"
os = "freebsd"

    [[WaveFD.download]]
    sha256 = "175ec98f673358ceb5333b0c1538e815ddfe9fd6a17c4d2ba92306eb6e5cca93"
    url = "https://github.com/JuliaBinaryWrappers/WaveFD_jll.jl/releases/download/WaveFD-v0.3.0+0/WaveFD.v0.3.0.x86_64-unknown-freebsd.tar.gz"
[[WaveFD]]
arch = "x86_64"
git-tree-sha1 = "4c655dadfa5977724a3231d94210dbcae2eeea95"
os = "windows"

    [[WaveFD.download]]
    sha256 = "dd5e45fba4b820778bc1a824e7a32d6f6c2c71269272fe0314f41b2bb581bed7"
    url = "https://github.com/JuliaBinaryWrappers/WaveFD_jll.jl/releases/download/WaveFD-v0.3.0+0/WaveFD.v0.3.0.x86_64-w64-mingw32.tar.gz"
