[[WaveFD]]
arch = "aarch64"
git-tree-sha1 = "9cfb99c5bc49906b2f52168984acbfdac18c1e28"
os = "macos"

    [[WaveFD.download]]
    sha256 = "fc7c2c8add9628a78530b78018f6c0bf1c8682f1f51c35194c4ab261ce8a5985"
    url = "https://github.com/JuliaBinaryWrappers/WaveFD_jll.jl/releases/download/WaveFD-v0.6.1+0/WaveFD.v0.6.1.aarch64-apple-darwin.tar.gz"
[[WaveFD]]
arch = "aarch64"
git-tree-sha1 = "7f892dd3f71194c6bf77aaab0dde8c17de1661dc"
libc = "glibc"
os = "linux"

    [[WaveFD.download]]
    sha256 = "7876fb281527f40a7d8fe00d1cf5a88a0d27953924739f451ce09c94d87893e1"
    url = "https://github.com/JuliaBinaryWrappers/WaveFD_jll.jl/releases/download/WaveFD-v0.6.1+0/WaveFD.v0.6.1.aarch64-linux-gnu.tar.gz"
[[WaveFD]]
arch = "aarch64"
git-tree-sha1 = "ad316f5a19efc2004bf34211b742fecc8e9d230e"
libc = "musl"
os = "linux"

    [[WaveFD.download]]
    sha256 = "a4739694c17e3b722fd8df99eb0a24ddf769bc3a01927180458b7ebafcc872fd"
    url = "https://github.com/JuliaBinaryWrappers/WaveFD_jll.jl/releases/download/WaveFD-v0.6.1+0/WaveFD.v0.6.1.aarch64-linux-musl.tar.gz"
[[WaveFD]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e0979c19ca7f4c0537e51ae3a7336fb36e7a6137"
libc = "glibc"
os = "linux"

    [[WaveFD.download]]
    sha256 = "23dba4a614898bdbf9b22d505d58134e6e1806a490cdd797df9d545931d880cb"
    url = "https://github.com/JuliaBinaryWrappers/WaveFD_jll.jl/releases/download/WaveFD-v0.6.1+0/WaveFD.v0.6.1.armv6l-linux-gnueabihf.tar.gz"
[[WaveFD]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f8f1cc5c12d626869dc0227e3224fc2745cc6000"
libc = "musl"
os = "linux"

    [[WaveFD.download]]
    sha256 = "0509e4c0dbe553f525210c45ddc8543ae18d6ccfb54c9053f075d8c949d1f659"
    url = "https://github.com/JuliaBinaryWrappers/WaveFD_jll.jl/releases/download/WaveFD-v0.6.1+0/WaveFD.v0.6.1.armv6l-linux-musleabihf.tar.gz"
[[WaveFD]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "49b3553bc2fe7123d3f4617e6771e09d71ee1355"
libc = "glibc"
os = "linux"

    [[WaveFD.download]]
    sha256 = "8660774bbe4162be2b69c467dbb5c73a32839bab54a7fad6efb874f4e054e19d"
    url = "https://github.com/JuliaBinaryWrappers/WaveFD_jll.jl/releases/download/WaveFD-v0.6.1+0/WaveFD.v0.6.1.armv7l-linux-gnueabihf.tar.gz"
[[WaveFD]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6c46eb09a6d3260e0752d6e7921bf700c3fcb30d"
libc = "musl"
os = "linux"

    [[WaveFD.download]]
    sha256 = "4007ea8be2757c75837656298bc81cdda162661fe31371b8d8d897fa58c7dd46"
    url = "https://github.com/JuliaBinaryWrappers/WaveFD_jll.jl/releases/download/WaveFD-v0.6.1+0/WaveFD.v0.6.1.armv7l-linux-musleabihf.tar.gz"
[[WaveFD]]
arch = "i686"
git-tree-sha1 = "fc53809a91e36fd2442abdf4d3eec4470fea5596"
libc = "glibc"
os = "linux"

    [[WaveFD.download]]
    sha256 = "9b3b4219ae7064238f2dceb9db331250fc5ec0a779b8ab299afc09aba16b318a"
    url = "https://github.com/JuliaBinaryWrappers/WaveFD_jll.jl/releases/download/WaveFD-v0.6.1+0/WaveFD.v0.6.1.i686-linux-gnu.tar.gz"
[[WaveFD]]
arch = "i686"
git-tree-sha1 = "70d0e7c6e19b8812503a1fb48fa051a14918e26c"
libc = "musl"
os = "linux"

    [[WaveFD.download]]
    sha256 = "b89aff2516393eefd302dfc564f1d69e21e76ba6800a494ac928e6b1b5d60fcc"
    url = "https://github.com/JuliaBinaryWrappers/WaveFD_jll.jl/releases/download/WaveFD-v0.6.1+0/WaveFD.v0.6.1.i686-linux-musl.tar.gz"
[[WaveFD]]
arch = "i686"
git-tree-sha1 = "177e0bd2160e35f5888562b7bb5ced4553bef24d"
os = "windows"

    [[WaveFD.download]]
    sha256 = "8c332c90578f206b8c63931c27d6866ab67c4f1fd096e37e7fcd5bdc2bfec64a"
    url = "https://github.com/JuliaBinaryWrappers/WaveFD_jll.jl/releases/download/WaveFD-v0.6.1+0/WaveFD.v0.6.1.i686-w64-mingw32.tar.gz"
[[WaveFD]]
arch = "powerpc64le"
git-tree-sha1 = "aecdd5c39f53ff43185783f7ebae85c19889e455"
libc = "glibc"
os = "linux"

    [[WaveFD.download]]
    sha256 = "da4aa1d30a79c3e430f80e5d94d7bcb386544089357e75b9127e48dc2ea716be"
    url = "https://github.com/JuliaBinaryWrappers/WaveFD_jll.jl/releases/download/WaveFD-v0.6.1+0/WaveFD.v0.6.1.powerpc64le-linux-gnu.tar.gz"
[[WaveFD]]
arch = "x86_64"
git-tree-sha1 = "d0826d966592253dff163959d568f77b72160ffd"
os = "macos"

    [[WaveFD.download]]
    sha256 = "ff84d5f881c0b69c6a9bcfea73c93e0011fb9f06afdcd059c3fefac9402ddf05"
    url = "https://github.com/JuliaBinaryWrappers/WaveFD_jll.jl/releases/download/WaveFD-v0.6.1+0/WaveFD.v0.6.1.x86_64-apple-darwin.tar.gz"
[[WaveFD]]
arch = "x86_64"
git-tree-sha1 = "bc50270ff78f86d71cf72959190f90c1c431750a"
libc = "glibc"
os = "linux"

    [[WaveFD.download]]
    sha256 = "46ac966b31e7df858bd2746f004e004a40813e10b3554f4099f8a90a464d1cc8"
    url = "https://github.com/JuliaBinaryWrappers/WaveFD_jll.jl/releases/download/WaveFD-v0.6.1+0/WaveFD.v0.6.1.x86_64-linux-gnu.tar.gz"
[[WaveFD]]
arch = "x86_64"
git-tree-sha1 = "f8f038e2236b29e8042ca5819478ca9b575c88c7"
libc = "musl"
os = "linux"

    [[WaveFD.download]]
    sha256 = "fe022d7ea0f9d520bbf95d9b8c8e31f070b67487839af078118b09c6c0412884"
    url = "https://github.com/JuliaBinaryWrappers/WaveFD_jll.jl/releases/download/WaveFD-v0.6.1+0/WaveFD.v0.6.1.x86_64-linux-musl.tar.gz"
[[WaveFD]]
arch = "x86_64"
git-tree-sha1 = "86b2d025e6246d5c99cf265e8b0dbc5f9da88215"
os = "freebsd"

    [[WaveFD.download]]
    sha256 = "37b886743463e634b0c7809537bc44a8ee2393153e4e00d2a06e70d35e038b13"
    url = "https://github.com/JuliaBinaryWrappers/WaveFD_jll.jl/releases/download/WaveFD-v0.6.1+0/WaveFD.v0.6.1.x86_64-unknown-freebsd.tar.gz"
[[WaveFD]]
arch = "x86_64"
git-tree-sha1 = "a4e123bdee9b2ef82f5e1403e67044fcfa282a5a"
os = "windows"

    [[WaveFD.download]]
    sha256 = "5b6e5ed329d4689ed43a05da091f0bd8397c645565b722b3b885be6b531b6e7b"
    url = "https://github.com/JuliaBinaryWrappers/WaveFD_jll.jl/releases/download/WaveFD-v0.6.1+0/WaveFD.v0.6.1.x86_64-w64-mingw32.tar.gz"
