[[WaveFD]]
arch = "aarch64"
git-tree-sha1 = "b314228794874eacfc7ec416bbe5c5a8a572f8b8"
libc = "glibc"
os = "linux"

    [[WaveFD.download]]
    sha256 = "09fe315e90c2abb56234dbcaa7fd3ec51a41d7ce076474f0fac8d88e56e3eb58"
    url = "https://github.com/JuliaBinaryWrappers/WaveFD_jll.jl/releases/download/WaveFD-v0.1.1+0/WaveFD.v0.1.1.aarch64-linux-gnu.tar.gz"
[[WaveFD]]
arch = "aarch64"
git-tree-sha1 = "886100081269396c666fb2d218163160196eba84"
libc = "musl"
os = "linux"

    [[WaveFD.download]]
    sha256 = "f18f90fdc293983e3c989ba4bee14813ec77c0b4201bb9db0170b9eb2aa7366b"
    url = "https://github.com/JuliaBinaryWrappers/WaveFD_jll.jl/releases/download/WaveFD-v0.1.1+0/WaveFD.v0.1.1.aarch64-linux-musl.tar.gz"
[[WaveFD]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3ff563fd30af678f231048d2fa5c20834900ae0c"
libc = "glibc"
os = "linux"

    [[WaveFD.download]]
    sha256 = "f7e17dc88ec8160acae91f257f4f5de2719d16966f3ec0b0b946e485c80690ae"
    url = "https://github.com/JuliaBinaryWrappers/WaveFD_jll.jl/releases/download/WaveFD-v0.1.1+0/WaveFD.v0.1.1.armv7l-linux-gnueabihf.tar.gz"
[[WaveFD]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ecf960584790db4f1d8448353da12128c0b8b805"
libc = "musl"
os = "linux"

    [[WaveFD.download]]
    sha256 = "08a4e252d3757d53764212fa4dfb7a49d52b49a26ad80218b0acd1c77989d30f"
    url = "https://github.com/JuliaBinaryWrappers/WaveFD_jll.jl/releases/download/WaveFD-v0.1.1+0/WaveFD.v0.1.1.armv7l-linux-musleabihf.tar.gz"
[[WaveFD]]
arch = "i686"
git-tree-sha1 = "eed317b6ef8d4ffa38bb0f8a167ecd65697bdd5b"
libc = "glibc"
os = "linux"

    [[WaveFD.download]]
    sha256 = "98fa0cc0c6e64dbffcdf7bd5c81ba362fdf6681a58305b91af30324fc77d6d15"
    url = "https://github.com/JuliaBinaryWrappers/WaveFD_jll.jl/releases/download/WaveFD-v0.1.1+0/WaveFD.v0.1.1.i686-linux-gnu.tar.gz"
[[WaveFD]]
arch = "i686"
git-tree-sha1 = "c22e44c928b8aa7f2cf1df2db3d5982fc8cff5e7"
libc = "musl"
os = "linux"

    [[WaveFD.download]]
    sha256 = "b6c2e61e4df86e690048ad517ff5883c45837ba29042d27d4623a0d5bd9c6c03"
    url = "https://github.com/JuliaBinaryWrappers/WaveFD_jll.jl/releases/download/WaveFD-v0.1.1+0/WaveFD.v0.1.1.i686-linux-musl.tar.gz"
[[WaveFD]]
arch = "i686"
git-tree-sha1 = "e49bb3f1d10745c240f2c5b696008acb2eb59148"
os = "windows"

    [[WaveFD.download]]
    sha256 = "4e27af23c6f54c0d07bf8474365f0e0d54bc442afb6be358bc68b1833e19f7bd"
    url = "https://github.com/JuliaBinaryWrappers/WaveFD_jll.jl/releases/download/WaveFD-v0.1.1+0/WaveFD.v0.1.1.i686-w64-mingw32.tar.gz"
[[WaveFD]]
arch = "powerpc64le"
git-tree-sha1 = "4e54b05c7e8787e2210ae9e685ac60e1c03e028f"
libc = "glibc"
os = "linux"

    [[WaveFD.download]]
    sha256 = "8eef44b2fd23a0d8384951c3a4f11ed2b4424f638d5ebaf2175398196a556f6c"
    url = "https://github.com/JuliaBinaryWrappers/WaveFD_jll.jl/releases/download/WaveFD-v0.1.1+0/WaveFD.v0.1.1.powerpc64le-linux-gnu.tar.gz"
[[WaveFD]]
arch = "x86_64"
git-tree-sha1 = "05948f90fd6d5726769f8c37cd8b118adab3ff7e"
os = "macos"

    [[WaveFD.download]]
    sha256 = "d1d08eac9723d915bf36e7012934fbbee44466bc25105020c42bbf962cf0de88"
    url = "https://github.com/JuliaBinaryWrappers/WaveFD_jll.jl/releases/download/WaveFD-v0.1.1+0/WaveFD.v0.1.1.x86_64-apple-darwin.tar.gz"
[[WaveFD]]
arch = "x86_64"
git-tree-sha1 = "d40c37bb4485fb4b0658520ab0b0fa6ecb1fe907"
libc = "glibc"
os = "linux"

    [[WaveFD.download]]
    sha256 = "f156aac9c1a924fd0d33d52fc8196f471a88049779a1e40514a008c271ca9194"
    url = "https://github.com/JuliaBinaryWrappers/WaveFD_jll.jl/releases/download/WaveFD-v0.1.1+0/WaveFD.v0.1.1.x86_64-linux-gnu.tar.gz"
[[WaveFD]]
arch = "x86_64"
git-tree-sha1 = "ff4cc86fbf34bfb4da7fec33bb71e99bb7971a69"
libc = "musl"
os = "linux"

    [[WaveFD.download]]
    sha256 = "a8271f0db76ea30751d96d1b9e646f9f0879af353cce1211f880c846b48a53c9"
    url = "https://github.com/JuliaBinaryWrappers/WaveFD_jll.jl/releases/download/WaveFD-v0.1.1+0/WaveFD.v0.1.1.x86_64-linux-musl.tar.gz"
[[WaveFD]]
arch = "x86_64"
git-tree-sha1 = "303862575645a7d1f097494057cdebf8d15a1b2d"
os = "freebsd"

    [[WaveFD.download]]
    sha256 = "cffa5c0234291ed74470b20cbb78495fb1b00d8602ef3f49975c0fd15e5c43ce"
    url = "https://github.com/JuliaBinaryWrappers/WaveFD_jll.jl/releases/download/WaveFD-v0.1.1+0/WaveFD.v0.1.1.x86_64-unknown-freebsd.tar.gz"
[[WaveFD]]
arch = "x86_64"
git-tree-sha1 = "c6239cbc4bcf214c6393b7b1b4e2104c3b3acb2b"
os = "windows"

    [[WaveFD.download]]
    sha256 = "29e240c937ad1e24186b544ab3caf9a95e95bc76fb736ee2ebeacf93756e0283"
    url = "https://github.com/JuliaBinaryWrappers/WaveFD_jll.jl/releases/download/WaveFD-v0.1.1+0/WaveFD.v0.1.1.x86_64-w64-mingw32.tar.gz"
