# Autogenerated wrapper script for WaveFD_jll for aarch64-apple-darwin
export libillumination, libprop2DAcoIsoDenQ_DEO2_FDTD, libprop2DAcoTTIDenQ_DEO2_FDTD, libprop2DAcoVTIDenQ_DEO2_FDTD, libprop3DAcoIsoDenQ_DEO2_FDTD, libprop3DAcoTTIDenQ_DEO2_FDTD, libprop3DAcoVTIDenQ_DEO2_FDTD, libspacetime

using LLVMOpenMP_jll
using FFTW_jll
JLLWrappers.@generate_wrapper_header("WaveFD")
JLLWrappers.@declare_library_product(libillumination, "@rpath/libillumination.dylib")
JLLWrappers.@declare_library_product(libprop2DAcoIsoDenQ_DEO2_FDTD, "@rpath/libprop2DAcoIsoDenQ_DEO2_FDTD.dylib")
JLLWrappers.@declare_library_product(libprop2DAcoTTIDenQ_DEO2_FDTD, "@rpath/libprop2DAcoTTIDenQ_DEO2_FDTD.dylib")
JLLWrappers.@declare_library_product(libprop2DAcoVTIDenQ_DEO2_FDTD, "@rpath/libprop2DAcoVTIDenQ_DEO2_FDTD.dylib")
JLLWrappers.@declare_library_product(libprop3DAcoIsoDenQ_DEO2_FDTD, "@rpath/libprop3DAcoIsoDenQ_DEO2_FDTD.dylib")
JLLWrappers.@declare_library_product(libprop3DAcoTTIDenQ_DEO2_FDTD, "@rpath/libprop3DAcoTTIDenQ_DEO2_FDTD.dylib")
JLLWrappers.@declare_library_product(libprop3DAcoVTIDenQ_DEO2_FDTD, "@rpath/libprop3DAcoVTIDenQ_DEO2_FDTD.dylib")
JLLWrappers.@declare_library_product(libspacetime, "@rpath/libspacetime.dylib")
function __init__()
    JLLWrappers.@generate_init_header(LLVMOpenMP_jll, FFTW_jll)
    JLLWrappers.@init_library_product(
        libillumination,
        "lib/libillumination.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libprop2DAcoIsoDenQ_DEO2_FDTD,
        "lib/libprop2DAcoIsoDenQ_DEO2_FDTD.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libprop2DAcoTTIDenQ_DEO2_FDTD,
        "lib/libprop2DAcoTTIDenQ_DEO2_FDTD.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libprop2DAcoVTIDenQ_DEO2_FDTD,
        "lib/libprop2DAcoVTIDenQ_DEO2_FDTD.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libprop3DAcoIsoDenQ_DEO2_FDTD,
        "lib/libprop3DAcoIsoDenQ_DEO2_FDTD.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libprop3DAcoTTIDenQ_DEO2_FDTD,
        "lib/libprop3DAcoTTIDenQ_DEO2_FDTD.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libprop3DAcoVTIDenQ_DEO2_FDTD,
        "lib/libprop3DAcoVTIDenQ_DEO2_FDTD.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libspacetime,
        "lib/libspacetime.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
